"""post image columns

Revision ID: 607a6d4e57ae
Revises: a40c8b94a056
Create Date: 2026-08-31 15:03:45.215225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607a6d4e57ae'
down_revision: Union[str, Sequence[str], None] = 'a40c8b94a056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default keeps the NOT NULL add safe if the table already has rows;
    # the app always writes real values, so it is only a backfill placeholder.
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('image_content_type', sa.String(length=40), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image_content_type')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
