"""add categories and blog view count

Revision ID: 1ce061737a47
Revises: 650678eaacc1
Create Date: 2026-07-28 00:41:41.263437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce061737a47'
down_revision: Union[str, Sequence[str], None] = '650678eaacc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blogs_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(
    "fk_blogs_category_id_categories",
    "categories",
    ["category_id"],
    ["id"],
    ondelete="SET NULL",
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(
    "fk_blogs_category_id_categories",
    type_="foreignkey",
)
        batch_op.drop_index(batch_op.f('ix_blogs_category_id'))
        batch_op.drop_column('category_id')
        batch_op.drop_column('view_count')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
