"""add index on blogs.created_at

Revision ID: c1f9cc6447cc
Revises: 01a89a7e8eef
Create Date: 2026-08-25 14:17:36.017469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f9cc6447cc'
down_revision: Union[str, Sequence[str], None] = '01a89a7e8eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blogs_created_at'), 'blogs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_created_at'), table_name='blogs')
    # ### end Alembic commands ###
